name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore CarSpot.Api.sln

      - name: Build
        run: dotnet build CarSpot.Api.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test CarSpot.Api.sln --no-restore --no-build --configuration Release --verbosity normal

      - name: Lint (if applicable)
        run: dotnet format --verify-no-changes
        
  auto-approve:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ success() && github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
